import { alias, to, prop } from './by'

export const alignContent = alias('alignContent')
export const alignItems = alias('alignItems')
export const alignSelf = alias('alignSelf')
export const background = alias('background')
export const backgroundBlendMode = alias('backgroundBlendMode')
export const backgroundClip = alias('backgroundClip')
export const backgroundColor = alias('backgroundColor')
export const backgroundImage = alias('backgroundImage')
export const backgroundOrigin = alias('backgroundOrigin')
export const backgroundPosition = alias('backgroundPosition')
export const backgroundRepeat = alias('backgroundRepeat')
export const backgroundSize = alias('backgroundSize')
export const border = alias('border')
export const borderBottom = alias('borderBottom')
export const borderBottomColor = alias('borderBottomColor')
export const borderBottomLeftRadius = alias('borderBottomLeftRadius')
export const borderBottomRightRadius = alias('borderBottomRightRadius')
export const borderBottomStyle = alias('borderBottomStyle')
export const borderBottomWidth = alias('borderBottomWidth')
export const borderColor = alias('borderColor')
export const borderLeft = alias('borderLeft')
export const borderLeftColor = alias('borderLeftColor')
export const borderLeftStyle = alias('borderLeftStyle')
export const borderLeftWidth = alias('borderLeftWidth')
export const borderRadius = alias('borderRadius')
export const borderRight = alias('borderRight')
export const borderRightColor = alias('borderRightColor')
export const borderRightStyle = alias('borderRightStyle')
export const borderRightWidth = alias('borderRightWidth')
export const borderStyle = alias('borderStyle')
export const borderTop = alias('borderTop')
export const borderTopColor = alias('borderTopColor')
export const borderTopLeftRadius = alias('borderTopLeftRadius')
export const borderTopRightRadius = alias('borderTopRightRadius')
export const borderTopStyle = alias('borderTopStyle')
export const borderTopWidth = alias('borderTopWidth')
export const borderWidth = alias('borderWidth')
export const bottom = alias('bottom')
export const boxShadow = alias('boxShadow')
export const boxSizing = to('box-sizing', prop('boxSizing', 'border-box'))
export const clear = alias('clear')
export const color = alias('color')
export const columnGap = alias('columnGap')
export const cursor = alias('cursor')
export const display = alias('display')
export const flex = alias('flex')
export const flexBasis = alias('flexBasis')
export const flexDirection = alias('flexDirection')
export const flexFlow = alias('flexFlow')
export const flexGrow = alias('flexGrow')
export const flexShrink = alias('flexShrink')
export const flexWrap = alias('flexWrap')
export const float = alias('float')
export const font = alias('font')
export const fontFamily = alias('fontFamily')
export const fontSize = alias('fontSize')
export const fontStyle = alias('fontStyle')
export const fontVariant = alias('fontVariant')
export const fontWeight = alias('fontWeight')
export const gap = alias('gap')
export const grid = alias('grid')
export const gridArea = alias('gridArea')
export const gridAutoColumns = alias('gridAutoColumns')
export const gridAutoFlow = alias('gridAutoFlow')
export const gridAutoRows = alias('gridAutoRows')
export const gridColumn = alias('gridColumn')
export const gridColumnEnd = alias('gridColumnEnd')
export const gridColumnGap = alias('gridColumnGap')
export const gridColumnStart = alias('gridColumnStart')
export const gridGap = alias('gridGap')
export const gridRow = alias('gridRow')
export const gridRowEnd = alias('gridRowEnd')
export const gridRowGap = alias('gridRowGap')
export const gridRowStart = alias('gridRowStart')
export const gridTemplate = alias('gridTemplate')
export const gridTemplateAreas = alias('gridTemplateAreas')
export const gridTemplateColumns = alias('gridTemplateColumns')
export const gridTemplateRows = alias('gridTemplateRows')
export const height = alias('height')
export const justifyContent = alias('justifyContent')
export const justifyItems = alias('justifyItems')
export const justifySelf = alias('justifySelf')
export const left = alias('left')
export const letterSpacing = alias('letterSpacing')
export const lineHeight = alias('lineHeight')
export const listStyle = alias('listStyle')
export const listStyleImage = alias('listStyleImage')
export const listStylePosition = alias('listStylePosition')
export const listStyleType = alias('listStyleType')
export const margin = alias('margin')
export const marginBottom = alias('marginBottom')
export const marginLeft = alias('marginLeft')
export const marginRight = alias('marginRight')
export const marginTop = alias('marginTop')

export const marginX = `
	${alias('marginX', 'margin-left')}
	${alias('marginX', 'margin-right')}
`

export const marginY = `
	${alias('marginY', 'margin-top')}
	${alias('marginY', 'margin-bottom')}
`

export const maxHeight = alias('maxHeight')
export const maxWidth = alias('maxWidth')
export const minHeight = alias('minHeight')
export const minWidth = alias('minWidth')
export const opacity = alias('opacity')
export const order = alias('order')
export const overflow = alias('overflow')
export const overflowX = alias('overflowX')
export const overflowY = alias('overflowY')
export const padding = alias('padding')
export const paddingBottom = alias('paddingBottom')
export const paddingLeft = alias('paddingLeft')
export const paddingRight = alias('paddingRight')
export const paddingTop = alias('paddingTop')

export const paddingX = `
	${alias('paddingX', 'padding-left')}
	${alias('paddingX', 'padding-right')}
`

export const paddingY = `
	${alias('paddingY', 'padding-top')}
	${alias('paddingY', 'padding-bottom')}
`

export const placeContent = alias('placeContent')
export const placeItems = alias('placeItems')
export const placeSelf = alias('placeSelf')
export const pointerEvents = alias('pointerEvents')
export const position = alias('position')
export const right = alias('right')
export const rowGap = alias('rowGap')
export const textAlign = alias('textAlign')
export const textDecoration = alias('textDecoration')
export const textOverflow = alias('textOverflow')
export const textShadow = alias('textShadow')
export const textTransform = alias('textTransform')
export const top = alias('top')
export const transform = alias('transform')
export const transformOrigin = alias('transformOrigin')
export const transition = alias('transition')
export const transitionDelay = alias('transitionDelay')
export const transitionDuration = alias('transitionDuration')
export const transitionProperty = alias('transitionProperty')
export const transitionTimingFunction = alias('transitionTimingFunction')
export const userSelect = alias('userSelect')
export const visibility = alias('visibility')
export const whiteSpace = alias('whiteSpace')
export const width = alias('width')
export const wordBreak = alias('wordBreak')
export const wordWrap = alias('wordWrap')
export const zIndex = alias('zIndex')
